version: "3"
services:
  api_server:
    build: .
    volumes:
      - .:/republic

    environment:
      TZ: Europe/Moscow

    command: sh -c "pnpm tsc -p tsconfig.json && republic-worker deploy data/contract-rs.zip"
    ports:
      - "38080:8080"
    restart: unless-stopped
